# Generated by Django 5.2.7 on 2025-11-07 12:42

import django_interval.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "apis_ontology",
            "0002_illustration_inscription_monument_object_objecttype_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="person",
            name="date_of_birth_date_from",
        ),
        migrations.RemoveField(
            model_name="person",
            name="date_of_birth_date_sort",
        ),
        migrations.RemoveField(
            model_name="person",
            name="date_of_birth_date_to",
        ),
        migrations.RemoveField(
            model_name="person",
            name="date_of_death_date_from",
        ),
        migrations.RemoveField(
            model_name="person",
            name="date_of_death_date_sort",
        ),
        migrations.RemoveField(
            model_name="person",
            name="date_of_death_date_to",
        ),
        migrations.RemoveField(
            model_name="versionperson",
            name="date_of_birth_date_from",
        ),
        migrations.RemoveField(
            model_name="versionperson",
            name="date_of_birth_date_sort",
        ),
        migrations.RemoveField(
            model_name="versionperson",
            name="date_of_birth_date_to",
        ),
        migrations.RemoveField(
            model_name="versionperson",
            name="date_of_death_date_from",
        ),
        migrations.RemoveField(
            model_name="versionperson",
            name="date_of_death_date_sort",
        ),
        migrations.RemoveField(
            model_name="versionperson",
            name="date_of_death_date_to",
        ),
        migrations.AddField(
            model_name="person",
            name="active_years_end",
            field=django_interval.fields.FuzzyDateParserField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="person",
            name="active_years_end_date_from",
            field=models.DateField(
                auto_created=True, blank=True, editable=False, null=True
            ),
        ),
        migrations.AddField(
            model_name="person",
            name="active_years_end_date_sort",
            field=models.DateField(
                auto_created=True, blank=True, editable=False, null=True
            ),
        ),
        migrations.AddField(
            model_name="person",
            name="active_years_end_date_to",
            field=models.DateField(
                auto_created=True, blank=True, editable=False, null=True
            ),
        ),
        migrations.AddField(
            model_name="person",
            name="active_years_start",
            field=django_interval.fields.FuzzyDateParserField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="person",
            name="active_years_start_date_from",
            field=models.DateField(
                auto_created=True, blank=True, editable=False, null=True
            ),
        ),
        migrations.AddField(
            model_name="person",
            name="active_years_start_date_sort",
            field=models.DateField(
                auto_created=True, blank=True, editable=False, null=True
            ),
        ),
        migrations.AddField(
            model_name="person",
            name="active_years_start_date_to",
            field=models.DateField(
                auto_created=True, blank=True, editable=False, null=True
            ),
        ),
        migrations.AddField(
            model_name="versionperson",
            name="active_years_end",
            field=django_interval.fields.FuzzyDateParserField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="versionperson",
            name="active_years_end_date_from",
            field=models.DateField(
                auto_created=True, blank=True, editable=False, null=True
            ),
        ),
        migrations.AddField(
            model_name="versionperson",
            name="active_years_end_date_sort",
            field=models.DateField(
                auto_created=True, blank=True, editable=False, null=True
            ),
        ),
        migrations.AddField(
            model_name="versionperson",
            name="active_years_end_date_to",
            field=models.DateField(
                auto_created=True, blank=True, editable=False, null=True
            ),
        ),
        migrations.AddField(
            model_name="versionperson",
            name="active_years_start",
            field=django_interval.fields.FuzzyDateParserField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="versionperson",
            name="active_years_start_date_from",
            field=models.DateField(
                auto_created=True, blank=True, editable=False, null=True
            ),
        ),
        migrations.AddField(
            model_name="versionperson",
            name="active_years_start_date_sort",
            field=models.DateField(
                auto_created=True, blank=True, editable=False, null=True
            ),
        ),
        migrations.AddField(
            model_name="versionperson",
            name="active_years_start_date_to",
            field=models.DateField(
                auto_created=True, blank=True, editable=False, null=True
            ),
        ),
        migrations.AlterField(
            model_name="person",
            name="date_of_birth",
            field=models.DateField(blank=True, null=True, verbose_name="date of birth"),
        ),
        migrations.AlterField(
            model_name="person",
            name="date_of_death",
            field=models.DateField(blank=True, null=True, verbose_name="date of death"),
        ),
        migrations.AlterField(
            model_name="versionperson",
            name="date_of_birth",
            field=models.DateField(blank=True, null=True, verbose_name="date of birth"),
        ),
        migrations.AlterField(
            model_name="versionperson",
            name="date_of_death",
            field=models.DateField(blank=True, null=True, verbose_name="date of death"),
        ),
    ]
