# Generated by Django 5.2.7 on 2025-11-07 12:53

import django.db.models.deletion
import simple_history.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("apis_ontology", "0003_remove_person_date_of_birth_date_from_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="person",
            name="dynasty",
            field=models.ManyToManyField(
                blank=True, null=True, to="apis_ontology.dynasty"
            ),
        ),
        migrations.AlterField(
            model_name="person",
            name="person_title",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="versionperson",
            name="person_title",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name="VersionPerson_dynasty",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                ("m2m_history_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "dynasty",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        db_tablespace="",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="apis_ontology.dynasty",
                    ),
                ),
                (
                    "history",
                    models.ForeignKey(
                        db_constraint=False,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="apis_ontology.versionperson",
                    ),
                ),
                (
                    "person",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        db_tablespace="",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="apis_ontology.person",
                    ),
                ),
            ],
            options={
                "verbose_name": "VersionPerson_dynasty",
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
