# Generated by Django 5.2.7 on 2025-11-11 04:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("apis_ontology", "0004_person_dynasty_alter_person_person_title_and_more"),
        ("relations", "0003_relation_relations_r_subj_content_type_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="PlaceLocatedInPlace",
            fields=[
                (
                    "relation_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="relations.relation",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("relations.relation",),
        ),
        migrations.AddField(
            model_name="place",
            name="alternative_names",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="versionplace",
            name="alternative_names",
            field=models.TextField(blank=True, null=True),
        ),
    ]
