# Generated by Django 5.2.7 on 2025-11-11 05:18

import django.db.models.deletion
import django_interval.fields
import simple_history.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("apis_ontology", "0006_inscriptionquotesassourcework"),
        ("relations", "0003_relation_relations_r_subj_content_type_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="InscriptionFoundInMonument",
            fields=[
                (
                    "relation_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="relations.relation",
                    ),
                ),
                ("position", models.CharField(blank=True, max_length=255, null=True)),
                ("reference", models.TextField(blank=True, null=True)),
            ],
            options={
                "abstract": False,
            },
            bases=("relations.relation",),
        ),
        migrations.CreateModel(
            name="InscriptionFoundInObject",
            fields=[
                (
                    "relation_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="relations.relation",
                    ),
                ),
                ("position", models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                "abstract": False,
            },
            bases=("relations.relation",),
        ),
        migrations.CreateModel(
            name="MonumentLocatedInPlace",
            fields=[
                (
                    "relation_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="relations.relation",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("relations.relation",),
        ),
        migrations.CreateModel(
            name="MonumentMentionedInInscription",
            fields=[
                (
                    "relation_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="relations.relation",
                    ),
                ),
                ("reference", models.TextField(blank=True, null=True)),
            ],
            options={
                "abstract": False,
            },
            bases=("relations.relation",),
        ),
        migrations.CreateModel(
            name="MonumentRelatedToInscription",
            fields=[
                (
                    "relation_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="relations.relation",
                    ),
                ),
                ("reference", models.TextField(blank=True, null=True)),
            ],
            options={
                "abstract": False,
            },
            bases=("relations.relation",),
        ),
        migrations.CreateModel(
            name="MonumentRepresentedAsIllustration",
            fields=[
                (
                    "relation_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="relations.relation",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("relations.relation",),
        ),
        migrations.CreateModel(
            name="ObjectMentionedInInscription",
            fields=[
                (
                    "relation_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="relations.relation",
                    ),
                ),
                ("reference", models.TextField(blank=True, null=True)),
            ],
            options={
                "abstract": False,
            },
            bases=("relations.relation",),
        ),
        migrations.CreateModel(
            name="ObjectPartOfMonument",
            fields=[
                (
                    "relation_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="relations.relation",
                    ),
                ),
                ("position", models.CharField(blank=True, max_length=255, null=True)),
                ("reference", models.TextField(blank=True, null=True)),
            ],
            options={
                "abstract": False,
            },
            bases=("relations.relation",),
        ),
        migrations.CreateModel(
            name="ObjectRelatedToInscription",
            fields=[
                (
                    "relation_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="relations.relation",
                    ),
                ),
                ("reference", models.TextField(blank=True, null=True)),
            ],
            options={
                "abstract": False,
            },
            bases=("relations.relation",),
        ),
        migrations.CreateModel(
            name="PersonMentionedInInscription",
            fields=[
                (
                    "relation_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="relations.relation",
                    ),
                ),
                ("reference", models.TextField(blank=True, null=True)),
            ],
            options={
                "abstract": False,
            },
            bases=("relations.relation",),
        ),
        migrations.CreateModel(
            name="PersonRelatedToInscription",
            fields=[
                (
                    "relation_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="relations.relation",
                    ),
                ),
                ("reference", models.TextField(blank=True, null=True)),
            ],
            options={
                "abstract": False,
            },
            bases=("relations.relation",),
        ),
        migrations.CreateModel(
            name="VersionInscription_diacritics",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                ("m2m_history_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "diacritics",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        db_tablespace="",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="apis_ontology.diacritics",
                    ),
                ),
            ],
            options={
                "verbose_name": "VersionInscription_diacritics",
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="VersionInscription_language",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                ("m2m_history_id", models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                "verbose_name": "VersionInscription_language",
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="VersionInscription_material",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                ("m2m_history_id", models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                "verbose_name": "VersionInscription_material",
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="VersionInscription_style",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                ("m2m_history_id", models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                "verbose_name": "VersionInscription_style",
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="VersionInscription_technique",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                ("m2m_history_id", models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                "verbose_name": "VersionInscription_technique",
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="VersionInscription_text_classification",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                ("m2m_history_id", models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                "verbose_name": "VersionInscription_text_classification",
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="VersionObject_material",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                ("m2m_history_id", models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                "verbose_name": "VersionObject_material",
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.DeleteModel(
            name="Ornaments",
        ),
        migrations.AddField(
            model_name="illustration",
            name="remarks",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="inscription",
            name="comparisons",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="inscription",
            name="date",
            field=django_interval.fields.FuzzyDateParserField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="inscription",
            name="date_date_from",
            field=models.DateField(
                auto_created=True, blank=True, editable=False, null=True
            ),
        ),
        migrations.AddField(
            model_name="inscription",
            name="date_date_sort",
            field=models.DateField(
                auto_created=True, blank=True, editable=False, null=True
            ),
        ),
        migrations.AddField(
            model_name="inscription",
            name="date_date_to",
            field=models.DateField(
                auto_created=True, blank=True, editable=False, null=True
            ),
        ),
        migrations.AddField(
            model_name="inscription",
            name="diacritics",
            field=models.ManyToManyField(blank=True, to="apis_ontology.diacritics"),
        ),
        migrations.AddField(
            model_name="inscription",
            name="dimensions_breadth",
            field=models.CharField(
                blank=True, help_text="in cm", max_length=255, null=True
            ),
        ),
        migrations.AddField(
            model_name="inscription",
            name="dimensions_height",
            field=models.CharField(
                blank=True, help_text="in cm", max_length=255, null=True
            ),
        ),
        migrations.AddField(
            model_name="inscription",
            name="dimensions_length",
            field=models.CharField(
                blank=True, help_text="in cm", max_length=255, null=True
            ),
        ),
        migrations.AddField(
            model_name="inscription",
            name="distribution",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="inscription",
            name="is_extant",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="inscription",
            name="language",
            field=models.ManyToManyField(blank=True, to="apis_ontology.language"),
        ),
        migrations.AddField(
            model_name="inscription",
            name="material",
            field=models.ManyToManyField(blank=True, to="apis_ontology.material"),
        ),
        migrations.AddField(
            model_name="inscription",
            name="ornaments",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="inscription",
            name="remarks",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="inscription",
            name="remarks_on_date",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="inscription",
            name="remarks_on_style_and_ornaments",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="inscription",
            name="style",
            field=models.ManyToManyField(blank=True, to="apis_ontology.style"),
        ),
        migrations.AddField(
            model_name="inscription",
            name="technique",
            field=models.ManyToManyField(blank=True, to="apis_ontology.technique"),
        ),
        migrations.AddField(
            model_name="inscription",
            name="text_classification",
            field=models.ManyToManyField(
                blank=True, to="apis_ontology.textclassification"
            ),
        ),
        migrations.AddField(
            model_name="inscription",
            name="text_original",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="inscription",
            name="text_translation",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="inscription",
            name="text_transliteration",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="monument",
            name="alternative_names",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="monument",
            name="is_extant",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="monument",
            name="remarks_on_preservation",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="object",
            name="dimensions_breadth",
            field=models.CharField(
                blank=True, help_text="in cm", max_length=255, null=True
            ),
        ),
        migrations.AddField(
            model_name="object",
            name="dimensions_height",
            field=models.CharField(
                blank=True, help_text="in cm", max_length=255, null=True
            ),
        ),
        migrations.AddField(
            model_name="object",
            name="dimensions_length",
            field=models.CharField(
                blank=True, help_text="in cm", max_length=255, null=True
            ),
        ),
        migrations.AddField(
            model_name="object",
            name="find_spot",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="object",
            name="is_extant",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="object",
            name="material",
            field=models.ManyToManyField(blank=True, to="apis_ontology.material"),
        ),
        migrations.AddField(
            model_name="object",
            name="object_type",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="object",
            name="remarks_on_preservation",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="versionillustration",
            name="remarks",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="versioninscription",
            name="comparisons",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="versioninscription",
            name="date",
            field=django_interval.fields.FuzzyDateParserField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="versioninscription",
            name="date_date_from",
            field=models.DateField(
                auto_created=True, blank=True, editable=False, null=True
            ),
        ),
        migrations.AddField(
            model_name="versioninscription",
            name="date_date_sort",
            field=models.DateField(
                auto_created=True, blank=True, editable=False, null=True
            ),
        ),
        migrations.AddField(
            model_name="versioninscription",
            name="date_date_to",
            field=models.DateField(
                auto_created=True, blank=True, editable=False, null=True
            ),
        ),
        migrations.AddField(
            model_name="versioninscription",
            name="dimensions_breadth",
            field=models.CharField(
                blank=True, help_text="in cm", max_length=255, null=True
            ),
        ),
        migrations.AddField(
            model_name="versioninscription",
            name="dimensions_height",
            field=models.CharField(
                blank=True, help_text="in cm", max_length=255, null=True
            ),
        ),
        migrations.AddField(
            model_name="versioninscription",
            name="dimensions_length",
            field=models.CharField(
                blank=True, help_text="in cm", max_length=255, null=True
            ),
        ),
        migrations.AddField(
            model_name="versioninscription",
            name="distribution",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="versioninscription",
            name="is_extant",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="versioninscription",
            name="ornaments",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="versioninscription",
            name="remarks",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="versioninscription",
            name="remarks_on_date",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="versioninscription",
            name="remarks_on_style_and_ornaments",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="versioninscription",
            name="text_original",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="versioninscription",
            name="text_translation",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="versioninscription",
            name="text_transliteration",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="versionmonument",
            name="alternative_names",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="versionmonument",
            name="is_extant",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="versionmonument",
            name="remarks_on_preservation",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="versionobject",
            name="dimensions_breadth",
            field=models.CharField(
                blank=True, help_text="in cm", max_length=255, null=True
            ),
        ),
        migrations.AddField(
            model_name="versionobject",
            name="dimensions_height",
            field=models.CharField(
                blank=True, help_text="in cm", max_length=255, null=True
            ),
        ),
        migrations.AddField(
            model_name="versionobject",
            name="dimensions_length",
            field=models.CharField(
                blank=True, help_text="in cm", max_length=255, null=True
            ),
        ),
        migrations.AddField(
            model_name="versionobject",
            name="find_spot",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="versionobject",
            name="is_extant",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="versionobject",
            name="object_type",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="versionobject",
            name="remarks_on_preservation",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="versioninscription_diacritics",
            name="history",
            field=models.ForeignKey(
                db_constraint=False,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="apis_ontology.versioninscription",
            ),
        ),
        migrations.AddField(
            model_name="versioninscription_diacritics",
            name="inscription",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                db_tablespace="",
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="apis_ontology.inscription",
            ),
        ),
        migrations.AddField(
            model_name="versioninscription_language",
            name="history",
            field=models.ForeignKey(
                db_constraint=False,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="apis_ontology.versioninscription",
            ),
        ),
        migrations.AddField(
            model_name="versioninscription_language",
            name="inscription",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                db_tablespace="",
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="apis_ontology.inscription",
            ),
        ),
        migrations.AddField(
            model_name="versioninscription_language",
            name="language",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                db_tablespace="",
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="apis_ontology.language",
            ),
        ),
        migrations.AddField(
            model_name="versioninscription_material",
            name="history",
            field=models.ForeignKey(
                db_constraint=False,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="apis_ontology.versioninscription",
            ),
        ),
        migrations.AddField(
            model_name="versioninscription_material",
            name="inscription",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                db_tablespace="",
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="apis_ontology.inscription",
            ),
        ),
        migrations.AddField(
            model_name="versioninscription_material",
            name="material",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                db_tablespace="",
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="apis_ontology.material",
            ),
        ),
        migrations.AddField(
            model_name="versioninscription_style",
            name="history",
            field=models.ForeignKey(
                db_constraint=False,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="apis_ontology.versioninscription",
            ),
        ),
        migrations.AddField(
            model_name="versioninscription_style",
            name="inscription",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                db_tablespace="",
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="apis_ontology.inscription",
            ),
        ),
        migrations.AddField(
            model_name="versioninscription_style",
            name="style",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                db_tablespace="",
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="apis_ontology.style",
            ),
        ),
        migrations.AddField(
            model_name="versioninscription_technique",
            name="history",
            field=models.ForeignKey(
                db_constraint=False,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="apis_ontology.versioninscription",
            ),
        ),
        migrations.AddField(
            model_name="versioninscription_technique",
            name="inscription",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                db_tablespace="",
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="apis_ontology.inscription",
            ),
        ),
        migrations.AddField(
            model_name="versioninscription_technique",
            name="technique",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                db_tablespace="",
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="apis_ontology.technique",
            ),
        ),
        migrations.AddField(
            model_name="versioninscription_text_classification",
            name="history",
            field=models.ForeignKey(
                db_constraint=False,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="apis_ontology.versioninscription",
            ),
        ),
        migrations.AddField(
            model_name="versioninscription_text_classification",
            name="inscription",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                db_tablespace="",
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="apis_ontology.inscription",
            ),
        ),
        migrations.AddField(
            model_name="versioninscription_text_classification",
            name="textclassification",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                db_tablespace="",
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="apis_ontology.textclassification",
            ),
        ),
        migrations.AddField(
            model_name="versionobject_material",
            name="history",
            field=models.ForeignKey(
                db_constraint=False,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="apis_ontology.versionobject",
            ),
        ),
        migrations.AddField(
            model_name="versionobject_material",
            name="material",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                db_tablespace="",
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="apis_ontology.material",
            ),
        ),
        migrations.AddField(
            model_name="versionobject_material",
            name="object",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                db_tablespace="",
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="apis_ontology.object",
            ),
        ),
    ]
