# Generated by Django 5.2.7 on 2025-11-14 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "apis_ontology",
            "0007_inscriptionfoundinmonument_inscriptionfoundinobject_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="personmentionedininscription",
            name="nisba",
            field=models.CharField(
                blank=True, help_text="Epithet", max_length=255, null=True
            ),
        ),
        migrations.AddField(
            model_name="personrelatedtoinscription",
            name="nisba",
            field=models.CharField(
                blank=True, help_text="Epithet", max_length=255, null=True
            ),
        ),
        migrations.AlterField(
            model_name="person",
            name="ism",
            field=models.CharField(
                blank=True, help_text="Forename", max_length=255, null=True
            ),
        ),
        migrations.AlterField(
            model_name="person",
            name="kunya",
            field=models.CharField(
                blank=True, help_text="Teknonym", max_length=255, null=True
            ),
        ),
        migrations.AlterField(
            model_name="person",
            name="nasab",
            field=models.CharField(
                blank=True,
                help_text="Patronymic, can be several, eg. name of father, grandfather, etc.",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="person",
            name="nisba",
            field=models.CharField(
                blank=True, help_text="Epithet", max_length=255, null=True
            ),
        ),
        migrations.AlterField(
            model_name="person",
            name="person_title",
            field=models.TextField(
                blank=True, help_text="one title per line", null=True
            ),
        ),
        migrations.AlterField(
            model_name="person",
            name="preferred_name",
            field=models.CharField(
                blank=True,
                help_text="If not provided, the name will be generated from the name parts.",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="versionperson",
            name="ism",
            field=models.CharField(
                blank=True, help_text="Forename", max_length=255, null=True
            ),
        ),
        migrations.AlterField(
            model_name="versionperson",
            name="kunya",
            field=models.CharField(
                blank=True, help_text="Teknonym", max_length=255, null=True
            ),
        ),
        migrations.AlterField(
            model_name="versionperson",
            name="nasab",
            field=models.CharField(
                blank=True,
                help_text="Patronymic, can be several, eg. name of father, grandfather, etc.",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="versionperson",
            name="nisba",
            field=models.CharField(
                blank=True, help_text="Epithet", max_length=255, null=True
            ),
        ),
        migrations.AlterField(
            model_name="versionperson",
            name="person_title",
            field=models.TextField(
                blank=True, help_text="one title per line", null=True
            ),
        ),
        migrations.AlterField(
            model_name="versionperson",
            name="preferred_name",
            field=models.CharField(
                blank=True,
                help_text="If not provided, the name will be generated from the name parts.",
                max_length=255,
                null=True,
            ),
        ),
    ]
