# Generated by Django 5.2.7 on 2025-11-24 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("apis_ontology", "0009_inscriptionrepresentedasillustration_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="monument",
            name="name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="versionmonument",
            name="name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
