# Generated by Django 5.2.7 on 2025-11-27 23:39

import django.db.models.deletion
import simple_history.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("apis_ontology", "0010_monument_name_versionmonument_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="monument",
            name="monument_type",
            field=models.ManyToManyField(blank=True, to="apis_ontology.monumenttype"),
        ),
        migrations.AddField(
            model_name="object",
            name="current_position",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="versionobject",
            name="current_position",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name="VersionMonument_monument_type",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                ("m2m_history_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "history",
                    models.ForeignKey(
                        db_constraint=False,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="apis_ontology.versionmonument",
                    ),
                ),
                (
                    "monument",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        db_tablespace="",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="apis_ontology.monument",
                    ),
                ),
                (
                    "monumenttype",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        db_tablespace="",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="apis_ontology.monumenttype",
                    ),
                ),
            ],
            options={
                "verbose_name": "VersionMonument_monument_type",
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
