# Generated by Django 5.2.7 on 2025-11-28 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "apis_ontology",
            "0011_monument_monument_type_object_current_position_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="person",
            name="date_of_birth",
        ),
        migrations.RemoveField(
            model_name="person",
            name="date_of_death",
        ),
        migrations.RemoveField(
            model_name="versionperson",
            name="date_of_birth",
        ),
        migrations.RemoveField(
            model_name="versionperson",
            name="date_of_death",
        ),
    ]
