# Generated by Django 5.2.7 on 2025-12-05 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("apis_ontology", "0012_remove_person_date_of_birth_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="PreservationState",
        ),
    ]
