# Generated by Django 5.2.7 on 2026-01-21 07:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("apis_ontology", "0014_inscriptionfoundinmonument_remarks_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="monument",
            name="preservation_state",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Excellent", "Excellent"),
                    ("Good", "Good"),
                    ("Medium", "Medium"),
                    ("Fragmentary", "Fragmentary"),
                    ("Poor", "Poor"),
                    ("Restored", "Restored"),
                    ("Not extant", "Not extant"),
                ],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="object",
            name="preservation_state",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Excellent", "Excellent"),
                    ("Good", "Good"),
                    ("Medium", "Medium"),
                    ("Fragmentary", "Fragmentary"),
                    ("Poor", "Poor"),
                    ("Restored", "Restored"),
                    ("Not extant", "Not extant"),
                ],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="versionmonument",
            name="preservation_state",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Excellent", "Excellent"),
                    ("Good", "Good"),
                    ("Medium", "Medium"),
                    ("Fragmentary", "Fragmentary"),
                    ("Poor", "Poor"),
                    ("Restored", "Restored"),
                    ("Not extant", "Not extant"),
                ],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="versionobject",
            name="preservation_state",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Excellent", "Excellent"),
                    ("Good", "Good"),
                    ("Medium", "Medium"),
                    ("Fragmentary", "Fragmentary"),
                    ("Poor", "Poor"),
                    ("Restored", "Restored"),
                    ("Not extant", "Not extant"),
                ],
                max_length=20,
                null=True,
            ),
        ),
    ]
