# Generated by Django 5.2.7 on 2026-01-21 07:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("apis_ontology", "0015_monument_preservation_state_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="inscription",
            name="preservation_state",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Excellent", "Excellent"),
                    ("Good", "Good"),
                    ("Medium", "Medium"),
                    ("Fragmentary", "Fragmentary"),
                    ("Poor", "Poor"),
                    ("Restored", "Restored"),
                    ("Not extant", "Not extant"),
                ],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="inscription",
            name="remarks_on_preservation",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="versioninscription",
            name="preservation_state",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Excellent", "Excellent"),
                    ("Good", "Good"),
                    ("Medium", "Medium"),
                    ("Fragmentary", "Fragmentary"),
                    ("Poor", "Poor"),
                    ("Restored", "Restored"),
                    ("Not extant", "Not extant"),
                ],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="versioninscription",
            name="remarks_on_preservation",
            field=models.TextField(blank=True, null=True),
        ),
    ]
