# Generated by Django 5.2.7 on 2026-01-21 07:31

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("apis_ontology", "0016_inscription_preservation_state_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="inscription",
            name="is_extant",
        ),
        migrations.RemoveField(
            model_name="monument",
            name="is_extant",
        ),
        migrations.RemoveField(
            model_name="object",
            name="is_extant",
        ),
        migrations.RemoveField(
            model_name="versioninscription",
            name="is_extant",
        ),
        migrations.RemoveField(
            model_name="versionmonument",
            name="is_extant",
        ),
        migrations.RemoveField(
            model_name="versionobject",
            name="is_extant",
        ),
    ]
