# Generated by Django 5.2.7 on 2026-01-21 07:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("apis_ontology", "0017_remove_inscription_is_extant_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="inscription",
            name="reference_tei",
            field=models.CharField(
                blank=True,
                help_text="reference to https://www.epigraphie-islamique.uliege.be/",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="versioninscription",
            name="reference_tei",
            field=models.CharField(
                blank=True,
                help_text="reference to https://www.epigraphie-islamique.uliege.be/",
                max_length=255,
                null=True,
            ),
        ),
    ]
