# Generated by Django 5.2.7 on 2026-01-21 08:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("apis_ontology", "0018_inscription_reference_tei_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="inscription",
            name="reference_tei",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                verbose_name="Thesaurus d'Epigraphie Islamique ID",
            ),
        ),
        migrations.AlterField(
            model_name="versioninscription",
            name="reference_tei",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                verbose_name="Thesaurus d'Epigraphie Islamique ID",
            ),
        ),
    ]
