# Generated by Django 5.2.7 on 2026-02-11 07:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("apis_ontology", "0019_alter_inscription_reference_tei_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="personmentionedininscription",
            name="dynasty",
            field=models.ManyToManyField(
                blank=True, null=True, to="apis_ontology.dynasty"
            ),
        ),
        migrations.AddField(
            model_name="personmentionedininscription",
            name="ism",
            field=models.CharField(
                blank=True, help_text="Forename", max_length=255, null=True
            ),
        ),
        migrations.AddField(
            model_name="personmentionedininscription",
            name="kunya",
            field=models.CharField(
                blank=True, help_text="Teknonym", max_length=255, null=True
            ),
        ),
        migrations.AddField(
            model_name="personmentionedininscription",
            name="nasab",
            field=models.CharField(
                blank=True,
                help_text="Patronymic, can be several, eg. name of father, grandfather, etc.",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="personmentionedininscription",
            name="person_role",
            field=models.ManyToManyField(blank=True, to="apis_ontology.personrole"),
        ),
        migrations.AddField(
            model_name="personmentionedininscription",
            name="person_title",
            field=models.TextField(
                blank=True, help_text="one title per line", null=True
            ),
        ),
        migrations.AddField(
            model_name="personmentionedininscription",
            name="relation_to_caliph",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="personrelatedtoinscription",
            name="dynasty",
            field=models.ManyToManyField(
                blank=True, null=True, to="apis_ontology.dynasty"
            ),
        ),
        migrations.AddField(
            model_name="personrelatedtoinscription",
            name="ism",
            field=models.CharField(
                blank=True, help_text="Forename", max_length=255, null=True
            ),
        ),
        migrations.AddField(
            model_name="personrelatedtoinscription",
            name="kunya",
            field=models.CharField(
                blank=True, help_text="Teknonym", max_length=255, null=True
            ),
        ),
        migrations.AddField(
            model_name="personrelatedtoinscription",
            name="nasab",
            field=models.CharField(
                blank=True,
                help_text="Patronymic, can be several, eg. name of father, grandfather, etc.",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="personrelatedtoinscription",
            name="person_role",
            field=models.ManyToManyField(blank=True, to="apis_ontology.personrole"),
        ),
        migrations.AddField(
            model_name="personrelatedtoinscription",
            name="person_title",
            field=models.TextField(
                blank=True, help_text="one title per line", null=True
            ),
        ),
        migrations.AddField(
            model_name="personrelatedtoinscription",
            name="relation_to_caliph",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
