# Generated by Django 5.2.7 on 2026-02-11 07:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("apis_ontology", "0020_personmentionedininscription_dynasty_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="person",
            name="dynasty",
            field=models.ManyToManyField(blank=True, to="apis_ontology.dynasty"),
        ),
        migrations.AlterField(
            model_name="personmentionedininscription",
            name="dynasty",
            field=models.ManyToManyField(blank=True, to="apis_ontology.dynasty"),
        ),
        migrations.AlterField(
            model_name="personrelatedtoinscription",
            name="dynasty",
            field=models.ManyToManyField(blank=True, to="apis_ontology.dynasty"),
        ),
    ]
