# Generated by Django 5.2.7 on 2026-03-05 05:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("apis_ontology", "0021_alter_person_dynasty_and_more"),
        ("relations", "0003_relation_relations_r_subj_content_type_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="PersonGrandparentOfPerson",
            fields=[
                (
                    "relation_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="relations.relation",
                    ),
                ),
                ("remarks", models.TextField(blank=True, null=True)),
            ],
            options={
                "abstract": False,
            },
            bases=("relations.relation", models.Model),
        ),
        migrations.CreateModel(
            name="PersonHusbandOfPerson",
            fields=[
                (
                    "relation_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="relations.relation",
                    ),
                ),
                ("remarks", models.TextField(blank=True, null=True)),
            ],
            options={
                "abstract": False,
            },
            bases=("relations.relation", models.Model),
        ),
        migrations.CreateModel(
            name="PersonIdenticalToPerson",
            fields=[
                (
                    "relation_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="relations.relation",
                    ),
                ),
                ("remarks", models.TextField(blank=True, null=True)),
            ],
            options={
                "abstract": False,
            },
            bases=("relations.relation", models.Model),
        ),
        migrations.CreateModel(
            name="PersonParentOfPerson",
            fields=[
                (
                    "relation_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="relations.relation",
                    ),
                ),
                ("remarks", models.TextField(blank=True, null=True)),
            ],
            options={
                "abstract": False,
            },
            bases=("relations.relation", models.Model),
        ),
        migrations.CreateModel(
            name="PersonSiblingOfPerson",
            fields=[
                (
                    "relation_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="relations.relation",
                    ),
                ),
                ("remarks", models.TextField(blank=True, null=True)),
            ],
            options={
                "abstract": False,
            },
            bases=("relations.relation", models.Model),
        ),
        migrations.CreateModel(
            name="PersonSubordinateOfPerson",
            fields=[
                (
                    "relation_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="relations.relation",
                    ),
                ),
                ("remarks", models.TextField(blank=True, null=True)),
            ],
            options={
                "abstract": False,
            },
            bases=("relations.relation", models.Model),
        ),
    ]
