# Generated by Django 5.2.7 on 2026-03-05 06:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "apis_ontology",
            "0022_persongrandparentofperson_personhusbandofperson_and_more",
        ),
        ("relations", "0003_relation_relations_r_subj_content_type_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="inscriptionquotesassourcework",
            name="remarks",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="personmentionedininscription",
            name="remarks",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="personrelatedtoinscription",
            name="remarks",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name="PersonMakerOfInscription",
            fields=[
                (
                    "relation_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="relations.relation",
                    ),
                ),
                (
                    "person_title",
                    models.TextField(
                        blank=True, help_text="one title per line", null=True
                    ),
                ),
                (
                    "kunya",
                    models.CharField(
                        blank=True, help_text="Teknonym", max_length=255, null=True
                    ),
                ),
                (
                    "ism",
                    models.CharField(
                        blank=True, help_text="Forename", max_length=255, null=True
                    ),
                ),
                (
                    "nasab",
                    models.CharField(
                        blank=True,
                        help_text="Patronymic, can be several, eg. name of father, grandfather, etc.",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "nisba",
                    models.CharField(
                        blank=True, help_text="Epithet", max_length=255, null=True
                    ),
                ),
                (
                    "relation_to_caliph",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("remarks", models.TextField(blank=True, null=True)),
                (
                    "dynasty",
                    models.ManyToManyField(blank=True, to="apis_ontology.dynasty"),
                ),
                (
                    "person_role",
                    models.ManyToManyField(blank=True, to="apis_ontology.personrole"),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("relations.relation", models.Model),
        ),
        migrations.CreateModel(
            name="PersonMakerOfMonument",
            fields=[
                (
                    "relation_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="relations.relation",
                    ),
                ),
                (
                    "person_title",
                    models.TextField(
                        blank=True, help_text="one title per line", null=True
                    ),
                ),
                (
                    "kunya",
                    models.CharField(
                        blank=True, help_text="Teknonym", max_length=255, null=True
                    ),
                ),
                (
                    "ism",
                    models.CharField(
                        blank=True, help_text="Forename", max_length=255, null=True
                    ),
                ),
                (
                    "nasab",
                    models.CharField(
                        blank=True,
                        help_text="Patronymic, can be several, eg. name of father, grandfather, etc.",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "nisba",
                    models.CharField(
                        blank=True, help_text="Epithet", max_length=255, null=True
                    ),
                ),
                (
                    "relation_to_caliph",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("remarks", models.TextField(blank=True, null=True)),
                (
                    "dynasty",
                    models.ManyToManyField(blank=True, to="apis_ontology.dynasty"),
                ),
                (
                    "person_role",
                    models.ManyToManyField(blank=True, to="apis_ontology.personrole"),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("relations.relation", models.Model),
        ),
        migrations.CreateModel(
            name="PersonMakerOfObject",
            fields=[
                (
                    "relation_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="relations.relation",
                    ),
                ),
                (
                    "person_title",
                    models.TextField(
                        blank=True, help_text="one title per line", null=True
                    ),
                ),
                (
                    "kunya",
                    models.CharField(
                        blank=True, help_text="Teknonym", max_length=255, null=True
                    ),
                ),
                (
                    "ism",
                    models.CharField(
                        blank=True, help_text="Forename", max_length=255, null=True
                    ),
                ),
                (
                    "nasab",
                    models.CharField(
                        blank=True,
                        help_text="Patronymic, can be several, eg. name of father, grandfather, etc.",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "nisba",
                    models.CharField(
                        blank=True, help_text="Epithet", max_length=255, null=True
                    ),
                ),
                (
                    "relation_to_caliph",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("remarks", models.TextField(blank=True, null=True)),
                (
                    "dynasty",
                    models.ManyToManyField(blank=True, to="apis_ontology.dynasty"),
                ),
                (
                    "person_role",
                    models.ManyToManyField(blank=True, to="apis_ontology.personrole"),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("relations.relation", models.Model),
        ),
        migrations.CreateModel(
            name="PersonRelatedToMonument",
            fields=[
                (
                    "relation_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="relations.relation",
                    ),
                ),
                (
                    "person_title",
                    models.TextField(
                        blank=True, help_text="one title per line", null=True
                    ),
                ),
                (
                    "kunya",
                    models.CharField(
                        blank=True, help_text="Teknonym", max_length=255, null=True
                    ),
                ),
                (
                    "ism",
                    models.CharField(
                        blank=True, help_text="Forename", max_length=255, null=True
                    ),
                ),
                (
                    "nasab",
                    models.CharField(
                        blank=True,
                        help_text="Patronymic, can be several, eg. name of father, grandfather, etc.",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "nisba",
                    models.CharField(
                        blank=True, help_text="Epithet", max_length=255, null=True
                    ),
                ),
                (
                    "relation_to_caliph",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("remarks", models.TextField(blank=True, null=True)),
                (
                    "dynasty",
                    models.ManyToManyField(blank=True, to="apis_ontology.dynasty"),
                ),
                (
                    "person_role",
                    models.ManyToManyField(blank=True, to="apis_ontology.personrole"),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("relations.relation", models.Model),
        ),
        migrations.CreateModel(
            name="PersonRelatedToObject",
            fields=[
                (
                    "relation_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="relations.relation",
                    ),
                ),
                (
                    "person_title",
                    models.TextField(
                        blank=True, help_text="one title per line", null=True
                    ),
                ),
                (
                    "kunya",
                    models.CharField(
                        blank=True, help_text="Teknonym", max_length=255, null=True
                    ),
                ),
                (
                    "ism",
                    models.CharField(
                        blank=True, help_text="Forename", max_length=255, null=True
                    ),
                ),
                (
                    "nasab",
                    models.CharField(
                        blank=True,
                        help_text="Patronymic, can be several, eg. name of father, grandfather, etc.",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "nisba",
                    models.CharField(
                        blank=True, help_text="Epithet", max_length=255, null=True
                    ),
                ),
                (
                    "relation_to_caliph",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("remarks", models.TextField(blank=True, null=True)),
                (
                    "dynasty",
                    models.ManyToManyField(blank=True, to="apis_ontology.dynasty"),
                ),
                (
                    "person_role",
                    models.ManyToManyField(blank=True, to="apis_ontology.personrole"),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("relations.relation", models.Model),
        ),
    ]
