# Generated by Django 5.2.7 on 2026-03-06 13:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("apis_ontology", "0023_inscriptionquotesassourcework_remarks_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="personmentionedininscription",
            name="benediction",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="personmentionedininscription",
            name="introduction",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
