# Generated by Django 6.0.3 on 2026-03-10 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("apis_ontology", "0024_personmentionedininscription_benediction_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="inscriptionquotesassourcework",
            name="reference",
            field=models.TextField(blank=True, null=True),
        ),
    ]
