# Generated by Django 6.0.3 on 2026-03-12 13:06
import logging
from django.db import migrations


logger = logging.getLogger(__name__)


def populate_object_type_vocab(apps, schema_editor):
    Object = apps.get_model("apis_ontology", "Object")
    ObjectType = apps.get_model("apis_ontology", "ObjectType")

    for obj in Object.objects.all():
        if not obj.object_type:
            continue
        match = ObjectType.objects.filter(label__icontains=obj.object_type).first()
        if match:
            obj.object_type_vocab_id = match.id
            obj.save(update_fields=["object_type_vocab"])
        else:
            logger.error(
                f"No match found for object '{obj}' with object_type '{obj.object_type}'"
            )


class Migration(migrations.Migration):

    dependencies = [
        ("apis_ontology", "0026_object_object_type_vocab_and_more"),
    ]
    operations = [
        migrations.RunPython(populate_object_type_vocab),
    ]
