# Generated by Django 6.0.3 on 2026-03-12 13:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("apis_ontology", "0027_populate_object_type_vocab"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="object",
            name="object_type",
        ),
        migrations.RemoveField(
            model_name="versionobject",
            name="object_type",
        ),
        migrations.AlterField(
            model_name="object",
            name="object_type_vocab",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="apis_ontology.objecttype",
            ),
        ),
        migrations.AlterField(
            model_name="versionobject",
            name="object_type_vocab",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="apis_ontology.objecttype",
            ),
        ),
    ]
