# Generated by Django 6.0.3 on 2026-03-12 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("apis_ontology", "0028_remove_object_object_type_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="object",
            old_name="object_type_vocab",
            new_name="object_type",
        ),
        migrations.RenameField(
            model_name="versionobject",
            old_name="object_type_vocab",
            new_name="object_type",
        ),
    ]
