# Generated by Django 6.0.3 on 2026-03-23 08:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("apis_ontology", "0029_rename_object_type_vocab_object_object_type_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="inscription",
            name="writing_field",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="versioninscription",
            name="writing_field",
            field=models.TextField(blank=True, null=True),
        ),
    ]
