# Generated by Django 6.0.3 on 2026-04-19 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("apis_ontology", "0031_monumentconnectedtomonument_objectconnectedtoobject"),
    ]

    operations = [
        migrations.CreateModel(
            name="Ornaments",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "label",
                    models.CharField(
                        blank=True, default="", max_length=4096, verbose_name="label"
                    ),
                ),
            ],
            options={
                "verbose_name": "ornament",
                "verbose_name_plural": "ornaments",
                "ordering": ["label"],
                "abstract": False,
            },
        ),
    ]