# Generated by Django 6.0.3 on 2026-05-15 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("apis_ontology", "0033_migrate_ornaments_data"),
    ]

    operations = [
        migrations.AddField(
            model_name="inscription",
            name="remarks_on_material_and_technique",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="versioninscription",
            name="remarks_on_material_and_technique",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="inscription",
            name="remarks",
            field=models.TextField(
                blank=True, null=True, verbose_name="remarks on text"
            ),
        ),
        migrations.AlterField(
            model_name="versioninscription",
            name="remarks",
            field=models.TextField(
                blank=True, null=True, verbose_name="remarks on text"
            ),
        ),
    ]
