# Generated by Django 5.2.15 on 2026-07-24 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("apis_ontology", "0036_objectfoundinmonument_objectpartofobject_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="person",
            old_name="person_title",
            new_name="honorifics",
        ),
        migrations.RenameField(
            model_name="personmakerofinscription",
            old_name="person_title",
            new_name="honorifics",
        ),
        migrations.RenameField(
            model_name="personmakerofmonument",
            old_name="person_title",
            new_name="honorifics",
        ),
        migrations.RenameField(
            model_name="personmakerofobject",
            old_name="person_title",
            new_name="honorifics",
        ),
        migrations.RenameField(
            model_name="personmentionedininscription",
            old_name="person_title",
            new_name="honorifics",
        ),
        migrations.RenameField(
            model_name="personrelatedtoinscription",
            old_name="person_title",
            new_name="honorifics",
        ),
        migrations.RenameField(
            model_name="personrelatedtomonument",
            old_name="person_title",
            new_name="honorifics",
        ),
        migrations.RenameField(
            model_name="personrelatedtoobject",
            old_name="person_title",
            new_name="honorifics",
        ),
        migrations.RenameField(
            model_name="versionperson",
            old_name="person_title",
            new_name="honorifics",
        ),
    ]
