# Generated by Django 5.2.15 on 2026-07-24 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("apis_ontology", "0037_rename_person_title_person_honorifics_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="person",
            name="honorifics",
            field=models.TextField(
                blank=True,
                help_text="one title per line",
                null=True,
                verbose_name="Honorifics (laqab)",
            ),
        ),
        migrations.AlterField(
            model_name="personmakerofinscription",
            name="honorifics",
            field=models.TextField(
                blank=True,
                help_text="one title per line",
                null=True,
                verbose_name="Honorifics (laqab)",
            ),
        ),
        migrations.AlterField(
            model_name="personmakerofmonument",
            name="honorifics",
            field=models.TextField(
                blank=True,
                help_text="one title per line",
                null=True,
                verbose_name="Honorifics (laqab)",
            ),
        ),
        migrations.AlterField(
            model_name="personmakerofobject",
            name="honorifics",
            field=models.TextField(
                blank=True,
                help_text="one title per line",
                null=True,
                verbose_name="Honorifics (laqab)",
            ),
        ),
        migrations.AlterField(
            model_name="personmentionedininscription",
            name="honorifics",
            field=models.TextField(
                blank=True,
                help_text="one title per line",
                null=True,
                verbose_name="Honorifics (laqab)",
            ),
        ),
        migrations.AlterField(
            model_name="personrelatedtoinscription",
            name="honorifics",
            field=models.TextField(
                blank=True,
                help_text="one title per line",
                null=True,
                verbose_name="Honorifics (laqab)",
            ),
        ),
        migrations.AlterField(
            model_name="personrelatedtomonument",
            name="honorifics",
            field=models.TextField(
                blank=True,
                help_text="one title per line",
                null=True,
                verbose_name="Honorifics (laqab)",
            ),
        ),
        migrations.AlterField(
            model_name="personrelatedtoobject",
            name="honorifics",
            field=models.TextField(
                blank=True,
                help_text="one title per line",
                null=True,
                verbose_name="Honorifics (laqab)",
            ),
        ),
        migrations.AlterField(
            model_name="versionperson",
            name="honorifics",
            field=models.TextField(
                blank=True,
                help_text="one title per line",
                null=True,
                verbose_name="Honorifics (laqab)",
            ),
        ),
    ]
