# Generated by Django 5.2.15 on 2026-07-24 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("apis_ontology", "0038_alter_person_honorifics_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="person",
            name="person_title",
            field=models.CharField(
                blank=True, help_text="Title", max_length=255, null=True
            ),
        ),
        migrations.AddField(
            model_name="personmakerofinscription",
            name="person_title",
            field=models.CharField(
                blank=True, help_text="Title", max_length=255, null=True
            ),
        ),
        migrations.AddField(
            model_name="personmakerofmonument",
            name="person_title",
            field=models.CharField(
                blank=True, help_text="Title", max_length=255, null=True
            ),
        ),
        migrations.AddField(
            model_name="personmakerofobject",
            name="person_title",
            field=models.CharField(
                blank=True, help_text="Title", max_length=255, null=True
            ),
        ),
        migrations.AddField(
            model_name="personmentionedininscription",
            name="person_title",
            field=models.CharField(
                blank=True, help_text="Title", max_length=255, null=True
            ),
        ),
        migrations.AddField(
            model_name="personrelatedtoinscription",
            name="person_title",
            field=models.CharField(
                blank=True, help_text="Title", max_length=255, null=True
            ),
        ),
        migrations.AddField(
            model_name="personrelatedtomonument",
            name="person_title",
            field=models.CharField(
                blank=True, help_text="Title", max_length=255, null=True
            ),
        ),
        migrations.AddField(
            model_name="personrelatedtoobject",
            name="person_title",
            field=models.CharField(
                blank=True, help_text="Title", max_length=255, null=True
            ),
        ),
        migrations.AddField(
            model_name="versionperson",
            name="person_title",
            field=models.CharField(
                blank=True, help_text="Title", max_length=255, null=True
            ),
        ),
    ]
