# Generated by Django 5.2.15 on 2026-09-18 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("apis_ontology", "0039_person_person_title_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="inscription",
            name="reading_author",
            field=models.TextField(
                blank=True, null=True, verbose_name="reading author"
            ),
        ),
        migrations.AddField(
            model_name="versioninscription",
            name="reading_author",
            field=models.TextField(
                blank=True, null=True, verbose_name="reading author"
            ),
        ),
    ]
