# Generated by Django 5.2.15 on 2026-09-18 07:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("apis_ontology", "0040_inscription_reading_author_and_more"),
        ("relations", "0003_relation_relations_r_subj_content_type_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ObjectRelatedToMonument",
            fields=[
                (
                    "relation_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="relations.relation",
                    ),
                ),
                ("remarks", models.TextField(blank=True, null=True)),
            ],
            options={
                "abstract": False,
            },
            bases=("relations.relation", models.Model),
        ),
        migrations.CreateModel(
            name="ObjectRelatedToPlace",
            fields=[
                (
                    "relation_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="relations.relation",
                    ),
                ),
                ("remarks", models.TextField(blank=True, null=True)),
            ],
            options={
                "abstract": False,
            },
            bases=("relations.relation", models.Model),
        ),
    ]
