# Generated by Django 5.2.15 on 2026-09-18 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("apis_ontology", "0041_objectrelatedtomonument_objectrelatedtoplace"),
    ]

    operations = [
        migrations.AddField(
            model_name="object",
            name="original_position",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="versionobject",
            name="original_position",
            field=models.TextField(blank=True, null=True),
        ),
    ]
