# Generated by Django 5.2.15 on 2026-09-18 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("apis_ontology", "0042_object_original_position_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="inscription",
            name="dimensions_breadth",
            field=models.CharField(
                blank=True,
                help_text="in cm",
                max_length=255,
                null=True,
                verbose_name="Breadth",
            ),
        ),
        migrations.AlterField(
            model_name="inscription",
            name="dimensions_height",
            field=models.CharField(
                blank=True,
                help_text="in cm",
                max_length=255,
                null=True,
                verbose_name="Height",
            ),
        ),
        migrations.AlterField(
            model_name="inscription",
            name="dimensions_length",
            field=models.CharField(
                blank=True,
                help_text="in cm",
                max_length=255,
                null=True,
                verbose_name="Length",
            ),
        ),
        migrations.AlterField(
            model_name="object",
            name="dimensions_breadth",
            field=models.CharField(
                blank=True,
                help_text="in cm",
                max_length=255,
                null=True,
                verbose_name="Breadth",
            ),
        ),
        migrations.AlterField(
            model_name="object",
            name="dimensions_height",
            field=models.CharField(
                blank=True,
                help_text="in cm",
                max_length=255,
                null=True,
                verbose_name="Height",
            ),
        ),
        migrations.AlterField(
            model_name="object",
            name="dimensions_length",
            field=models.CharField(
                blank=True,
                help_text="in cm",
                max_length=255,
                null=True,
                verbose_name="Length",
            ),
        ),
        migrations.AlterField(
            model_name="versioninscription",
            name="dimensions_breadth",
            field=models.CharField(
                blank=True,
                help_text="in cm",
                max_length=255,
                null=True,
                verbose_name="Breadth",
            ),
        ),
        migrations.AlterField(
            model_name="versioninscription",
            name="dimensions_height",
            field=models.CharField(
                blank=True,
                help_text="in cm",
                max_length=255,
                null=True,
                verbose_name="Height",
            ),
        ),
        migrations.AlterField(
            model_name="versioninscription",
            name="dimensions_length",
            field=models.CharField(
                blank=True,
                help_text="in cm",
                max_length=255,
                null=True,
                verbose_name="Length",
            ),
        ),
        migrations.AlterField(
            model_name="versionobject",
            name="dimensions_breadth",
            field=models.CharField(
                blank=True,
                help_text="in cm",
                max_length=255,
                null=True,
                verbose_name="Breadth",
            ),
        ),
        migrations.AlterField(
            model_name="versionobject",
            name="dimensions_height",
            field=models.CharField(
                blank=True,
                help_text="in cm",
                max_length=255,
                null=True,
                verbose_name="Height",
            ),
        ),
        migrations.AlterField(
            model_name="versionobject",
            name="dimensions_length",
            field=models.CharField(
                blank=True,
                help_text="in cm",
                max_length=255,
                null=True,
                verbose_name="Length",
            ),
        ),
    ]
